// Vue.js/jumpup-vuecli2/src/App.vue
<template>
  <div id="app">
    <div id="background" style="background-image: url('./assets/background.jpg');">
      <div id="container">
        <Header />
        <Content />
        <Footer />
      </div>
    </div>
  </div>
</template>

<script>
import Header from "./components/header.vue";
import Content from "./components/content.vue";
import Footer from "./components/footer.vue";
import './reset.css';
import './global.css';

export default {
  name: 'App',
  components: {
    Header,
    Content,
    Footer,
  }
}
</script>

<style>
</style>

// React.js/jumpup-react/src/App.jsx
import './reset.css';
import './global.css';
import './App.css';

import Header from './components/header';
import Content from "./components/content";
import Footer from "./components/footer";

function App() {

  const style = {
    backgroundImage: "url('./assets/background.jpg')",
  };

  return (
    <div className="App">
      <div id="background" style={style}>
        <div id="container">
          <Header />
          <Content />
          <Footer />
        </div>
      </div>
    </div>
  );
}

export default App;
